argo-cd:
  installCRDs: false
  dex:
    enabled: false
  controller:
    args:
      statusProcessors: 20
      operationProcessors: 50
      appResyncPeriod: 60
    extraArgs: ['--repo-server-timeout-seconds', '420']
    env:
      - name: "ARGOCD_SYNC_WAVE_DELAY"
        value: "15"
  server:
    service:
      type: NodePort
    extraArgs:
      - --insecure  
    ingress:
      enabled: false
    config:
      repositories: |
        - type: helm
          name: stable
          url: https://charts.helm.sh/stable/
        - type: helm
          name: argo-cd
          url: https://argoproj.github.io/argo-helm
        - type: helm
          name: jetstack
          url: https://charts.jetstack.io
      # pass server url via terraform
      url:

targetgroupbinding:
  enabled: false
  annotations: {}
  targetgroup:
    arn:
